"""initial schema

Revision ID: 46402cc9793a
Revises: 
Create Date: 2026-07-02 19:31:15.985771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '46402cc9793a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dmc_packages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dmc_account_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('destination', sa.String(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('total_price_lkr', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ota_platforms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('base_url', sa.String(), nullable=False),
    sa.Column('scrape_config', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_markets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('country_name', sa.String(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('locale', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('analysis_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=True),
    sa.Column('source_market_ids', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('total_tasks', sa.Integer(), nullable=True),
    sa.Column('completed_tasks', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_log', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['dmc_packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competitiveness_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=True),
    sa.Column('source_market_id', sa.Integer(), nullable=True),
    sa.Column('dmc_price_usd', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('market_assembled_price_usd', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('price_delta_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['dmc_packages.id'], ),
    sa.ForeignKeyConstraint(['source_market_id'], ['source_markets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reports_package', 'competitiveness_reports', ['package_id', sa.literal_column('generated_at DESC')], unique=False)
    op.create_table('package_components',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('component_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('nights_or_duration', sa.String(), nullable=True),
    sa.Column('base_price_lkr', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['dmc_packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scrape_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=True),
    sa.Column('source_market_id', sa.Integer(), nullable=True),
    sa.Column('proxy_session_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_log', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['platform_id'], ['ota_platforms.id'], ),
    sa.ForeignKeyConstraint(['source_market_id'], ['source_markets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ota_listings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scrape_session_id', sa.Integer(), nullable=True),
    sa.Column('platform_id', sa.Integer(), nullable=True),
    sa.Column('source_market_id', sa.Integer(), nullable=True),
    sa.Column('component_type', sa.String(), nullable=False),
    sa.Column('raw_name', sa.String(), nullable=False),
    sa.Column('raw_description', sa.String(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('price_usd', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['platform_id'], ['ota_platforms.id'], ),
    sa.ForeignKeyConstraint(['scrape_session_id'], ['scrape_sessions.id'], ),
    sa.ForeignKeyConstraint(['source_market_id'], ['source_markets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ota_listings_captured', 'ota_listings', ['captured_at'], unique=False)
    op.create_index('idx_ota_listings_market', 'ota_listings', ['source_market_id', 'platform_id'], unique=False)
    op.create_table('component_matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('package_component_id', sa.Integer(), nullable=True),
    sa.Column('ota_listing_id', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('match_method', sa.String(), nullable=True),
    sa.Column('reviewed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['ota_listing_id'], ['ota_listings.id'], ),
    sa.ForeignKeyConstraint(['package_component_id'], ['package_components.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_component_matches_pkg', 'component_matches', ['package_component_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_component_matches_pkg', table_name='component_matches')
    op.drop_table('component_matches')
    op.drop_index('idx_ota_listings_market', table_name='ota_listings')
    op.drop_index('idx_ota_listings_captured', table_name='ota_listings')
    op.drop_table('ota_listings')
    op.drop_table('scrape_sessions')
    op.drop_table('package_components')
    op.drop_index('idx_reports_package', table_name='competitiveness_reports')
    op.drop_table('competitiveness_reports')
    op.drop_table('analysis_jobs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('source_markets')
    op.drop_table('ota_platforms')
    op.drop_table('dmc_packages')
    # ### end Alembic commands ###
