"""Change dmc_account_id to UUID

Revision ID: 4af4521e5147
Revises: 46402cc9793a
Create Date: 2026-07-03 01:40:57.003280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4af4521e5147'
down_revision: Union[str, None] = '46402cc9793a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('TRUNCATE TABLE dmc_packages CASCADE')
    op.alter_column('dmc_packages', 'dmc_account_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using='dmc_account_id::text::uuid')
    op.create_foreign_key(None, 'dmc_packages', 'users', ['dmc_account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dmc_packages', type_='foreignkey')
    op.alter_column('dmc_packages', 'dmc_account_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
